var cityList = [
    {code:"",label:"Select A City"},
    {code:"NA",label: "Alaska", state:"Alaska"},
    {code:"13",label:"AK Anchorage", state:"Alaska"},
    {code:"487",label:"AK Anchorage-Fairbanks-Juneau", state:"Alaska"},
    {code:"14",label:"AK Fairbanks", state:"Alaska"},
    {code:"15",label:"AK Juneau", state:"Alaska"},
    {code:"16",label:"AK Kodiak", state:"Alaska"},
    {code:"NA",label: "Alabama"},
    {code:"3",label:"AL Anniston-Calhoun County", state:"Alabama"},
    {code:"4",label:"AL Auburn-Opelika", state:"Alabama"},
    {code:"5",label:"AL Birmingham", state:"Alabama"},
    {code:"6",label:"AL Decatur-Hartselle", state:"Alabama"},
    {code:"7",label:"AL Dothan", state:"Alabama"},
    {code:"8",label:"AL Florence", state:"Alabama"},
    {code:"9",label:"AL Huntsville", state:"Alabama"},
    {code:"10",label:"AL Mobile", state:"Alabama"},
    {code:"11",label:"AL Montgomery", state:"Alabama"},
    {code:"12",label:"AL Tuscaloosa", state:"Alabama"},
    {code:"NA",label: "Arkansas"},
    {code:"526",label:"AR Bentonville", state:"Arkansas"},
    {code:"28",label:"AR Conway", state:"Arkansas"},
    {code:"24",label:"AR Fayetteville", state:"Arkansas"},
    {code:"26",label:"AR Hot Springs", state:"Arkansas"},
    {code:"27",label:"AR Jonesboro", state:"Arkansas"},
    {code:"29",label:"AR Little Rock-N Little Rock", state:"Arkansas"},
    {code:"472",label:"AR Paragould", state:"Arkansas"},
    {code:"NA",label: "Arizona"},
    {code:"444",label:"AZ Bullhead City", state:"Arizona"},
    {code:"17",label:"AZ Flagstaff", state:"Arizona"},
    {code:"18",label:"AZ Lake Havasu City", state:"Arizona"},
    {code:"19",label:"AZ Phoenix", state:"Arizona"},
    {code:"20",label:"AZ Prescott-Prescott Valley", state:"Arizona"},
    {code:"445",label:"AZ Scottsdale", state:"Arizona"},
    {code:"21",label:"AZ Sierra Vista", state:"Arizona"},
    {code:"522",label:"AZ Surprise", state:"Arizona"},
    {code:"22",label:"AZ Tucson", state:"Arizona"},
    {code:"23",label:"AZ Yuma", state:"Arizona"},
    {code:"NA",label: "California"},
    {code:"30",label:"CA Bakersfield", state:"California"},
    {code:"31",label:"CA Fresno", state:"California"},
    {code:"32",label:"CA Los Angeles-Long Beach", state:"California"},
    {code:"497",label:"CA Modesto", state:"California"},
    {code:"33",label:"CA Oakland", state:"California"},
    {code:"42",label:"CA Orange County", state:"California"},
    {code:"34",label:"CA Palm Springs", state:"California"},
    {code:"35",label:"CA Riverside City", state:"California"},
    {code:"37",label:"CA Sacramento", state:"California"},
    {code:"38",label:"CA San Diego", state:"California"},
    {code:"39",label:"CA San Francisco", state:"California"},
    {code:"40",label:"CA San Jose", state:"California"},
    {code:"482",label:"CA Stockton", state:"California"},
    {code:"511",label:"CA Sunnyvale", state:"California"},
    {code:"483",label:"CA Tracy", state:"California"},
    {code:"383",label:"CA Truckee-Nevada County", state:"California"},
    {code:"NA",label: "Colorado"},
    {code:"43",label:"CO Colorado Springs", state:"Colorado"},
    {code:"44",label:"CO Denver", state:"Colorado"},
    {code:"50",label:"CO Glenwood Springs", state:"Colorado"},
    {code:"47",label:"CO Grand Junction", state:"Colorado"},
    {code:"51",label:"CO Gunnison", state:"Colorado"},
    {code:"49",label:"CO Pueblo", state:"Colorado"},
    {code:"523",label:"CO Westminster", state:"Colorado"},
    {code:"NA",label: "Connecticut"},
    {code:"53",label:"CT Hartford", state:"Connecticut"},
    {code:"54",label:"CT New Haven", state:"Connecticut"},
    {code:"52",label:"CT Stamford", state:"Connecticut"},
    {code:"NA",label: "District Of Columbia"},
    {code:"59",label:"DC-VA Washington-Arlington-Alexandria", state:"District Of Columbia"},
    {code:"NA",label: "Delaware"}, 
    {code:"56",label:"DE Dover", state:"Delaware"},
    {code:"524",label:"DE Sussex County", state:"Delaware"},
    {code:"58",label:"DE Wilmington", state:"Delaware"},
    {code:"NA",label: "Florida"},
    {code:"70",label:"FL Bradenton", state:"Florida"},
    {code:"60",label:"FL Cape Coral-Fort Myers", state:"Florida"},
    {code:"437",label:"FL Daytona Beach", state:"Florida"},
    {code:"61",label:"FL Fort Lauderdale", state:"Florida"},
    {code:"63",label:"FL Gainesville", state:"Florida"},
    {code:"64",label:"FL Jacksonville", state:"Florida"},
    {code:"65",label:"FL Miami-Dade County", state:"Florida"},
    {code:"66",label:"FL Orlando", state:"Florida"},
    {code:"403",label:"FL Palm Coast-Flagler County", state:"Florida"},
    {code:"502",label:"FL Pensacola", state:"Florida"},
    {code:"427",label:"FL Punta Gorda-Charlotte Co", state:"Florida"},
    {code:"71",label:"FL Sarasota", state:"Florida"},
    {code:"467",label:"FL Tallahassee", state:"Florida"},
    {code:"73",label:"FL Tampa", state:"Florida"},
    {code:"74",label:"FL Vero Beach-Indian River", state:"Florida"},
    {code:"NA",label: "Georgia"},
    {code:"76",label:"GA Albany", state:"Georgia"},
    {code:"78",label:"GA Atlanta", state:"Georgia"},
    {code:"498",label:"GA Columbus", state:"Georgia"},
    {code:"446",label:"GA Dalton", state:"Georgia"},
    {code:"473",label:"GA Dublin-Laurens County", state:"Georgia"},
    {code:"461",label:"GA Fayetteville-Fayette County", state:"Georgia"},
    {code:"515",label:"GA LaGrange-Troup County", state:"Georgia"},
    {code:"79",label:"GA Marietta", state:"Georgia"},
    {code:"84",label:"GA Savannah", state:"Georgia"},
    {code:"527",label:"GA Screven County", state:"Georgia"},
    {code:"488",label:"GA Statesboro-Bulloch County", state:"Georgia"},
    {code:"86",label:"GA Valdosta", state:"Georgia"},
    {code:"80",label:"GA-SC Augusta-Aiken", state:"Georgia"},
    {code:"NA",label: "Hawaii"},
    {code:"468",label:"HI Hilo", state:"Hawaii"},
    {code:"88",label:"HI Honolulu", state:"Hawaii"},
    {code:"NA",label: "Iowa"},
    {code:"111",label:"IA Ames", state:"Iowa"},
    {code:"112",label:"IA Burlington", state:"Iowa"},
    {code:"462",label:"IA Carroll County", state:"Iowa"},
    {code:"113",label:"IA Cedar Rapids", state:"Iowa"},
    {code:"115",label:"IA Des Moines", state:"Iowa"},
    {code:"116",label:"IA Dubuque", state:"Iowa"},
    {code:"463",label:"IA Estherville", state:"Iowa"},
    {code:"378",label:"IA Iowa City", state:"Iowa"},
    {code:"117",label:"IA Mason City", state:"Iowa"},
    {code:"554",label:"IA Sioux City", state:"Iowa"},
    {code:"464",label:"IA Spencer", state:"Iowa"},
    {code:"465",label:"IA Spirit Lake", state:"Iowa"},
    {code:"466",label:"IA Storm Lake", state:"Iowa"},
    {code:"118",label:"IA Waterloo-Cedar Falls", state:"Iowa"},
    {code:"114",label:"IA-IL Davenport-Moline-Rock Is", state:"Iowa"},
    {code:"NA",label: "Idaho"},
    {code:"89",label:"ID Boise", state:"Idaho"},
    {code:"90",label:"ID Idaho Falls", state:"Idaho"},
    {code:"91",label:"ID Twin Falls", state:"Idaho"},
    {code:"NA",label: "Illinois"},
    {code:"559",label:"IL Bloomington-Normal", state:"Illinois"},
    {code:"439",label:"IL Carbondale", state:"Illinois"},
    {code:"93",label:"IL Champaign-Urbana", state:"Illinois"},
    {code:"94",label:"IL Chicago", state:"Illinois"},
    {code:"96",label:"IL Danville", state:"Illinois"},
    {code:"97",label:"IL Decatur", state:"Illinois"},
    {code:"98",label:"IL Galesburg", state:"Illinois"},
    {code:"95",label:"IL Joliet-Will County", state:"Illinois"},
    {code:"447",label:"IL Kankakee", state:"Illinois"},
    {code:"99",label:"IL Peoria", state:"Illinois"},
    {code:"100",label:"IL Quincy", state:"Illinois"},
    {code:"349",label:"IL Rockford", state:"Illinois"},
    {code:"101",label:"IL Springfield", state:"Illinois"},
    {code:"NA",label: "Indiana"},
    {code:"455",label:"IN Bloomington", state:"Indiana"},
    {code:"396",label:"IN Elkhart-Goshen", state:"Indiana"},
    {code:"103",label:"IN Evansville", state:"Indiana"},
    {code:"104",label:"IN Fort Wayne-Allen County", state:"Indiana"},
    {code:"106",label:"IN Indianapolis", state:"Indiana"},
    {code:"448",label:"IN Indianapolis-Morgan County", state:"Indiana"},
    {code:"532",label:"IN Kokomo", state:"Indiana"},
    {code:"107",label:"IN Lafayette", state:"Indiana"},
    {code:"108",label:"IN Muncie", state:"Indiana"},
    {code:"400",label:"IN Richmond", state:"Indiana"},
    {code:"109",label:"IN South Bend", state:"Indiana"},
    {code:"495",label:"IN Terre Haute", state:"Indiana"},
    {code:"458",label:"IN Warsaw", state:"Indiana"},
    {code:"459",label:"IN Winona Lake", state:"Indiana"},
    {code:"NA",label: "Kansas"},
    {code:"119",label:"KS Dodge City", state:"Kansas"},
    {code:"122",label:"KS Hutchinson", state:"Kansas"},
    {code:"124",label:"KS Manhattan", state:"Kansas"},
    {code:"393",label:"KS Miami County", state:"Kansas"},
    {code:"489",label:"KS Pittsburg", state:"Kansas"},
    {code:"125",label:"KS Salina", state:"Kansas"},
    {code:"126",label:"KS Topeka", state:"Kansas"},
    {code:"127",label:"KS Wichita", state:"Kansas"},
    {code:"NA",label: "Kentucky", state:"Kentucky"},
    {code:"469",label:"KY Ashland", state:"Kentucky"},
    {code:"128",label:"KY Bowling Green", state:"Kentucky"},
    {code:"129",label:"KY Covington", state:"Kentucky"},
    {code:"131",label:"KY Lexington", state:"Kentucky"},
    {code:"132",label:"KY Louisville", state:"Kentucky"},
    {code:"433",label:"KY Madisonville", state:"Kentucky"},
    {code:"133",label:"KY Paducah", state:"Kentucky"},
    {code:"NA",label: "Louisiana", },
    {code:"353",label:"LA Alexandria", state:"Louisiana"},
    {code:"134",label:"LA Baton Rouge", state:"Louisiana"},
    {code:"397",label:"LA Hammond", state:"Louisiana"},
    {code:"414",label:"LA Houma-Terrebonne Parish", state:"Louisiana"},
    {code:"135",label:"LA Lafayette", state:"Louisiana"},
    {code:"136",label:"LA Lake Charles", state:"Louisiana"},
    {code:"354",label:"LA Monroe", state:"Louisiana"},
    {code:"470",label:"LA New Orleans", state:"Louisiana"},
    {code:"138",label:"LA Shreveport-Bossier City", state:"Louisiana"},
    {code:"137",label:"LA Slidell - St Tammany Parish", state:"Louisiana"},
    {code:"493",label:"LA Thibodaux-Lafourche Parish", state:"Louisiana"},
    {code:"NA",label: "Massachusetts"},
    {code:"143",label:"MA Boston", state:"Massachusetts"},
    {code:"146",label:"MA Fitchburg-Leominster", state:"Massachusetts"},
    {code:"144",label:"MA Framingham-Natick", state:"Massachusetts"},
    {code:"530",label:"MA Nantucket", state:"Massachusetts"},
    {code:"145",label:"MA Pittsfield-Berkshire County", state:"Massachusetts"},
    {code:"NA",label: "Maryland"},
    {code:"141",label:"MD Baltimore", state:"Maryland"},
    {code:"142",label:"MD Bethesda-Gaithersburg-Frederick", state:"Maryland"},
    {code:"484",label:"MD Charles County", state:"Maryland"},
    {code:"NA",label: "Maine"},
    {code:"140",label:"ME Portland", state:"Maine"},
    {code:"NA",label: "Michigan"},
    {code:"434",label:"MI Ann Arbor", state:"Michigan"},
    {code:"485",label:"MI Benton Harbor", state:"Michigan"},
    {code:"147",label:"MI Detroit", state:"Michigan"},
    {code:"148",label:"MI Grand Rapids", state:"Michigan"},
    {code:"395",label:"MI Houghton", state:"Michigan"},
    {code:"150",label:"MI Kalamazoo", state:"Michigan"},
    {code:"507",label:"MI Lansing", state:"Michigan"},
    {code:"512",label:"MI Troy", state:"Michigan"},
    {code:"NA",label: "Minnesota"},
    {code:"386",label:"MN Mankato", state:"Minnesota"},
    {code:"356",label:"MN Minneapolis", state:"Minnesota"},
    {code:"151",label:"MN Rochester", state:"Minnesota"},
    {code:"152",label:"MN St. Cloud", state:"Minnesota"},
    {code:"364",label:"MN St. Paul", state:"Minnesota"},
    {code:"NA",label: "Missouri"},
    {code:"565",label:"MO Branson", state:"Missouri"},
    {code:"158",label:"MO Columbia", state:"Missouri"},
    {code:"159",label:"MO Jefferson City", state:"Missouri"},
    {code:"160",label:"MO Joplin", state:"Missouri"},
    {code:"435",label:"MO Rolla", state:"Missouri"},
    {code:"164",label:"MO Springfield", state:"Missouri"},
    {code:"162",label:"MO St. Joseph", state:"Missouri"},
    {code:"163",label:"MO-IL St. Louis", state:"Missouri"},
    {code:"161",label:"MO-KS Kansas City", state:"Missouri"},
    {code:"NA",label: "Mississippi"},
    {code:"513",label:"MS Gulfport-Biloxi", state:"Mississippi"},
    {code:"154",label:"MS Hattiesburg", state:"Mississippi"},
    {code:"155",label:"MS Jackson", state:"Mississippi"},
    {code:"533",label:"MS Meridian", state:"Mississippi"},
    {code:"157",label:"MS Tupelo", state:"Mississippi"},
    {code:"NA",label: "Montana"},
    {code:"166",label:"MT Bozeman", state:"Montana"},
    {code:"560",label:"MT Great Falls", state:"Montana"},
    {code:"167",label:"MT Kalispell", state:"Montana"},
    {code:"168",label:"MT Missoula", state:"Montana"},
    {code:"NA",label: "North Carolina"},
    {code:"190",label:"NC Asheville", state:"North Carolina"},
    {code:"191",label:"NC Burlington", state:"North Carolina"},
    {code:"194",label:"NC Chapel Hill", state:"North Carolina"},
    {code:"192",label:"NC Charlotte", state:"North Carolina"},
    {code:"200",label:"NC Dare County", state:"North Carolina"},
    {code:"195",label:"NC Durham", state:"North Carolina"},
    {code:"352",label:"NC Fayetteville", state:"North Carolina"},
    {code:"197",label:"NC Greenville", state:"North Carolina"},
    {code:"198",label:"NC Hickory", state:"North Carolina"},
    {code:"357",label:"NC Jacksonville", state:"North Carolina"},
    {code:"202",label:"NC Lexington-Thomasville", state:"North Carolina"},
    {code:"207",label:"NC Marion-McDowell County", state:"North Carolina"},
    {code:"203",label:"NC Raleigh", state:"North Carolina"},
    {code:"535",label:"NC Salisbury", state:"North Carolina"},
    {code:"205",label:"NC Wilmington", state:"North Carolina"},
    {code:"206",label:"NC Winston-Salem", state:"North Carolina"},
    {code:"NA",label: "North Dakota"},
    {code:"208",label:"ND Bismarck-Mandan", state:"North Dakota"},
    {code:"514",label:"ND Grand Forks", state:"North Dakota"},
    {code:"211",label:"ND Minot", state:"North Dakota"},
    {code:"209",label:"ND-MN Fargo-Moorhead", state:"North Dakota"},
    {code:"NA",label: "Nebraska"},
    {code:"169",label:"NE Hastings", state:"Nebraska"},
    {code:"404",label:"NE Lincoln", state:"Nebraska"},
    {code:"170",label:"NE Omaha", state:"Nebraska"},
    {code:"NA",label: "New Hampshire"},
    {code:"350",label:"NH Manchester", state:"New Hampshire"},
    {code:"NA",label: "New Jersey"},
    {code:"175",label:"NJ Bergen-Passaic", state:"New Jersey"},
    {code:"173",label:"NJ Middlesex-Monmouth", state:"New Jersey"},
    {code:"534",label:"NJ Morristown", state:"New Jersey"},
    {code:"174",label:"NJ Newark-Elizabeth", state:"New Jersey"},
    {code:"561",label:"NJ Vineland", state:"New Jersey"},
    {code:"NA",label: "New Mexico"},
    {code:"503",label:"NM Albuquerque", state:"New Mexico"},
    {code:"351",label:"NM Carlsbad", state:"New Mexico"},
    {code:"179",label:"NM Las Cruces", state:"New Mexico"},
    {code:"180",label:"NM Los Alamos", state:"New Mexico"},
    {code:"177",label:"NM Rio Rancho", state:"New Mexico"},
    {code:"NA",label: "Nevada"},
    {code:"171",label:"NV Las Vegas", state:"Nevada"},
    {code:"172",label:"NV Reno-Sparks", state:"Nevada"},
    {code:"NA",label: "New York", state:"New York"},
    {code:"373",label:"NY Albany", state:"New York"},
    {code:"181",label:"NY Buffalo", state:"New York"},
    {code:"474",label:"NY Dutchess County", state:"New York"},
    {code:"183",label:"NY Ithaca", state:"New York"},
    {code:"184",label:"NY Nassau County", state:"New York"},
    {code:"389",label:"NY New York (Brooklyn)", state:"New York"},
    {code:"185",label:"NY New York (Manhattan)", state:"New York"},
    {code:"186",label:"NY New York (Queens)", state:"New York"},
    {code:"188",label:"NY Rochester", state:"New York"},
    {code:"189",label:"NY Syracuse", state:"New York"},
    {code:"456",label:"NY Utica-Rome", state:"New York"},
    {code:"NA",label: "Ohio"},
    {code:"212",label:"OH Akron", state:"Ohio"},
    {code:"213",label:"OH Ashland", state:"Ohio"},
    {code:"214",label:"OH Cincinnati", state:"Ohio"},
    {code:"215",label:"OH Cleveland", state:"Ohio"},
    {code:"216",label:"OH Columbus", state:"Ohio"},
    {code:"217",label:"OH Dayton", state:"Ohio"},
    {code:"218",label:"OH Findlay", state:"Ohio"},
    {code:"219",label:"OH Lima", state:"Ohio"},
    {code:"358",label:"OH Wayne County", state:"Ohio"},
    {code:"429",label:"OH Wooster", state:"Ohio"},
    {code:"222",label:"OH Youngstown-Warren", state:"Ohio"},
    {code:"NA",label: "Oklahoma"},
    {code:"431",label:"OK Ada", state:"Oklahoma"},
    {code:"223",label:"OK Ardmore", state:"Oklahoma"},
    {code:"228",label:"OK Edmond", state:"Oklahoma"},
    {code:"224",label:"OK Enid", state:"Oklahoma"},
    {code:"225",label:"OK Lawton", state:"Oklahoma"},
    {code:"471",label:"OK McAlester", state:"Oklahoma"},
    {code:"227",label:"OK Muskogee", state:"Oklahoma"},
    {code:"229",label:"OK Norman", state:"Oklahoma"},
    {code:"230",label:"OK Oklahoma City", state:"Oklahoma"},
    {code:"231",label:"OK Ponca City", state:"Oklahoma"},
    {code:"235",label:"OK Pryor Creek", state:"Oklahoma"},
    {code:"232",label:"OK Stillwater", state:"Oklahoma"},
    {code:"234",label:"OK Tulsa", state:"Oklahoma"},
    {code:"NA",label: "Oregon"},
    {code:"405",label:"OR Klamath Falls", state:"Oregon"},
    {code:"239",label:"OR Portland", state:"Oregon"},
    {code:"NA",label: "Pennsylvania"},
    {code:"440",label:"PA Allentown", state:"Pennsylvania"},
    {code:"241",label:"PA Erie", state:"Pennsylvania"},
    {code:"402",label:"PA Harrisburg", state:"Pennsylvania"},
    {code:"242",label:"PA Indiana County", state:"Pennsylvania"},
    {code:"243",label:"PA Johnstown", state:"Pennsylvania"},
    {code:"245",label:"PA Philadelphia", state:"Pennsylvania"},
    {code:"246",label:"PA Pittsburgh", state:"Pennsylvania"},
    {code:"528",label:"PA Reading", state:"Pennsylvania"},
    {code:"499",label:"PA Scranton", state:"Pennsylvania"},
    {code:"500",label:"PA Wilkes-Barre", state:"Pennsylvania"},
    {code:"247",label:"PA Williamsport-Lycoming Co", state:"Pennsylvania"},
    {code:"248",label:"PA York County", state:"Pennsylvania"},
    {code:"NA",label: "Puerto Rico"},
    {code:"492",label:"PR San Juan", state:"Puerto Rico"},
    {code:"NA",label: "Rhode Island"},
    {code:"249",label:"RI Providence", state:"Rhode Island"},
    {code:"NA",label: "South Carolina"},
    {code:"250",label:"SC Anderson", state:"South Carolina"},
    {code:"381",label:"SC Beaufort", state:"South Carolina"},
    {code:"252",label:"SC Camden", state:"South Carolina"},
    {code:"251",label:"SC Charleston-N Charleston", state:"South Carolina"},
    {code:"253",label:"SC Columbia", state:"South Carolina"},
    {code:"255",label:"SC Greenville", state:"South Carolina"},
    {code:"256",label:"SC Hilton Head Island", state:"South Carolina"},
    {code:"258",label:"SC Myrtle Beach", state:"South Carolina"},
    {code:"457",label:"SC Spartanburg", state:"South Carolina"},
    {code:"260",label:"SC Sumter", state:"South Carolina"},
    {code:"NA",label: "South Dakota"},
    {code:"409",label:"SD Pierre", state:"South Dakota"},
    {code:"410",label:"SD Rapid City", state:"South Dakota"},
    {code:"261",label:"SD Sioux Falls", state:"South Dakota"},
    {code:"NA",label: "Tennessee"},
    {code:"504",label:"TN Anderson County", state:"Tennessee"},
    {code:"519",label:"TN Campbell County", state:"Tennessee"},
    {code:"505",label:"TN Carter County", state:"Tennessee"},
    {code:"263",label:"TN Chattanooga", state:"Tennessee"},
    {code:"360",label:"TN Clarksville", state:"Tennessee"},
    {code:"264",label:"TN Cleveland", state:"Tennessee"},
    {code:"496",label:"TN Columbia-Maury County", state:"Tennessee"},
    {code:"265",label:"TN Cookeville", state:"Tennessee"},
    {code:"417",label:"TN Cumberland County", state:"Tennessee"},
    {code:"266",label:"TN Dyersburg", state:"Tennessee"},
    {code:"476",label:"TN Hamblen County", state:"Tennessee"},
    {code:"419",label:"TN Hamilton County", state:"Tennessee"},
    {code:"420",label:"TN Hardin County", state:"Tennessee"},
    {code:"520",label:"TN Henderson County", state:"Tennessee"},
    {code:"267",label:"TN Jackson-Madison County", state:"Tennessee"},
    {code:"422",label:"TN Jefferson County", state:"Tennessee"},
    {code:"268",label:"TN Johnson City", state:"Tennessee"},
    {code:"556",label:"TN Kingsport", state:"Tennessee"},
    {code:"270",label:"TN Knoxville", state:"Tennessee"},
    {code:"412",label:"TN Loudon County", state:"Tennessee"},
    {code:"564",label:"TN Maryville", state:"Tennessee"},
    {code:"477",label:"TN Maury County", state:"Tennessee"},
    {code:"271",label:"TN Memphis", state:"Tennessee"},
    {code:"521",label:"TN Monroe County", state:"Tennessee"},
    {code:"272",label:"TN Morristown", state:"Tennessee"},
    {code:"274",label:"TN Murfreesboro-Smyrna", state:"Tennessee"},
    {code:"275",label:"TN Nashville-Franklin", state:"Tennessee"},
    {code:"424",label:"TN Putnam County", state:"Tennessee"},
    {code:"479",label:"TN Roane County", state:"Tennessee"},
    {code:"425",label:"TN Robertson County", state:"Tennessee"},
    {code:"426",label:"TN Sullivan County", state:"Tennessee"},
    {code:"506",label:"TN Sumner County", state:"Tennessee"},
    {code:"518",label:"TN Unicoi County", state:"Tennessee"},
    {code:"480",label:"TN Warren County", state:"Tennessee"},
    {code:"510",label:"TN Washington County", state:"Tennessee"},
    {code:"NA",label: "Texas"},
    {code:"490",label:"TX Abilene", state:"Texas"},
    {code:"501",label:"TX Allen", state:"Texas"},
    {code:"277",label:"TX Amarillo", state:"Texas"},
    {code:"407",label:"TX Athens/Henderson County", state:"Texas"},
    {code:"278",label:"TX Austin", state:"Texas"},
    {code:"281",label:"TX Beaumont", state:"Texas"},
    {code:"453",label:"TX Belton", state:"Texas"},
    {code:"398",label:"TX Brazoria County", state:"Texas"},
    {code:"282",label:"TX Brownsville", state:"Texas"},
    {code:"555",label:"TX Cedar Park", state:"Texas"},
    {code:"292",label:"TX Conroe", state:"Texas"},
    {code:"284",label:"TX Corpus Christi", state:"Texas"},
    {code:"285",label:"TX Dallas", state:"Texas"},
    {code:"406",label:"TX Denton", state:"Texas"},
    {code:"288",label:"TX El Paso", state:"Texas"},
    {code:"290",label:"TX Fort Worth", state:"Texas"},
    {code:"283",label:"TX Harlingen", state:"Texas"},
    {code:"293",label:"TX Houston", state:"Texas"},
    {code:"370",label:"TX Hutto", state:"Texas"},
    {code:"529",label:"TX Kyle", state:"Texas"},
    {code:"486",label:"TX Longview", state:"Texas"},
    {code:"297",label:"TX Lubbock", state:"Texas"},
    {code:"298",label:"TX Lufkin", state:"Texas"},
    {code:"299",label:"TX McAllen", state:"Texas"},
    {code:"300",label:"TX Midland", state:"Texas"},
    {code:"391",label:"TX Nacogdoches", state:"Texas"},
    {code:"301",label:"TX Odessa", state:"Texas"},
    {code:"382",label:"TX Paris", state:"Texas"},
    {code:"286",label:"TX Plano", state:"Texas"},
    {code:"279",label:"TX Round Rock", state:"Texas"},
    {code:"304",label:"TX San Angelo", state:"Texas"},
    {code:"305",label:"TX San Antonio", state:"Texas"},
    {code:"280",label:"TX San Marcos", state:"Texas"},
    {code:"365",label:"TX Seguin", state:"Texas"},
    {code:"430",label:"TX Sherman-Denison", state:"Texas"},
    {code:"294",label:"TX Temple", state:"Texas"},
    {code:"308",label:"TX Tyler", state:"Texas"},
    {code:"310",label:"TX Waco", state:"Texas"},
    {code:"291",label:"TX Weatherford", state:"Texas"},
    {code:"366",label:"TX Wichita Falls", state:"Texas"},
    {code:"307",label:"TX-AR Texarkana", state:"Texas"},
    {code:"NA",label: "Utah"},
    {code:"311",label:"UT Cedar City", state:"Utah"},
    {code:"452",label:"UT Nephi", state:"Utah"},
    {code:"436",label:"UT Ogden", state:"Utah"},
    {code:"442",label:"UT Provo-Orem", state:"Utah"},
    {code:"314",label:"UT Salt Lake City", state:"Utah"},
    {code:"313",label:"UT St. George", state:"Utah"},
    {code:"NA",label: "Virginia"},
    {code:"508",label:"VA Alexandria", state:"Virginia"},
    {code:"509",label:"VA Arlington", state:"Virginia"},
    {code:"367",label:"VA Blacksburg", state:"Virginia"},
    {code:"316",label:"VA Charlottesville", state:"Virginia"},
    {code:"408",label:"VA Danville City", state:"Virginia"},
    {code:"322",label:"VA Hampton Roads-SE Virginia", state:"Virginia"},
    {code:"317",label:"VA Harrisonburg-Rockingham", state:"Virginia"},
    {code:"324",label:"VA Lexington-Buena Vista-Rockbridge", state:"Virginia"},
    {code:"368",label:"VA Lynchburg", state:"Virginia"},
    {code:"318",label:"VA Martinsville-Henry County", state:"Virginia"},
    {code:"319",label:"VA Richmond", state:"Virginia"},
    {code:"320",label:"VA Roanoke", state:"Virginia"},
    {code:"321",label:"VA Staunton-Waynesboro-Augusta", state:"Virginia"},
    {code:"361",label:"VA-WV Winchester", state:"Virginia"},
    {code:"NA",label: "Vermont"},
    {code:"315",label:"VT Burlington-Chittenden Co", state:"Vermont"},
    {code:"NA",label: "Washington"},
    {code:"325",label:"WA Bellingham", state:"Washington"},
    {code:"392",label:"WA Everett", state:"Washington"},
    {code:"443",label:"WA Moses Lake", state:"Washington"},
    {code:"494",label:"WA Mount Vernon-Skagit County", state:"Washington"},
    {code:"327",label:"WA Olympia", state:"Washington"},
    {code:"326",label:"WA Richland-Kennewick-Pasco", state:"Washington"},
    {code:"516",label:"WA San Juan County", state:"Washington"},
    {code:"329",label:"WA Seattle", state:"Washington"},
    {code:"330",label:"WA Spokane", state:"Washington"},
    {code:"331",label:"WA Tacoma", state:"Washington"},
    {code:"328",label:"WA Vancouver", state:"Washington"},
    {code:"525",label:"WA Wenatchee", state:"Washington"},
    {code:"362",label:"WA Yakima", state:"Washington"},
    {code:"NA",label: "Wisconsin"},
    {code:"337",label:"WI Eau Claire", state:"Wisconsin"},
    {code:"491",label:"WI Fond du Lac", state:"Wisconsin"},
    {code:"338",label:"WI Green Bay", state:"Wisconsin"},
    {code:"339",label:"WI Janesville", state:"Wisconsin"},
    {code:"416",label:"WI Madison", state:"Wisconsin"},
    {code:"344",label:"WI Marshfield", state:"Wisconsin"},
    {code:"340",label:"WI Milwaukee-Waukesha", state:"Wisconsin"},
    {code:"343",label:"WI Wausau", state:"Wisconsin"},
    {code:"NA",label: "Wyoming"},
    {code:"375",label:"WV Clarksburg", state:"Wyoming"},
    {code:"334",label:"WV Martinsburg-Berkeley County", state:"Wyoming"},
    {code:"333",label:"WV Morgantown", state:"Wyoming"},
    {code:"553",label:"WY Casper", state:"Wyoming"},
    {code:"345",label:"WY Cheyenne", state:"Wyoming"},
    {code:"347",label:"WY Larami", state:"Wyoming"},
    {code:"NA",label: "USA"},
    {code:"1",label:"USA National Average", state:"USA"}
    ];

    export default cityList;
